Ai Added
Counselllor/Counsellor-Web pull request #1316
Opened 2024-07-30 06:47 UTC by dhruv8433

# Description

@thestarsahil 

Azure Chat bot by Microsoft #1225

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1225(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/user-attachments/assets/459211d8-75d1-4b8c-96b5-7477828c022a

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

2024-07-30 06:48 UTC, dhruv8433 commented
@thestarsahil 

kindly please check this and merge it

2024-07-30 10:51 UTC, thestarsahil commented
Dear that's a reference not to copy and paste 
UI , Proper responsive need to work on

2024-07-31 06:13 UTC, dhruv8433 commented
@thestarsahil 

please check this 
i added fully functional chatbot 

https://github.com/user-attachments/assets/62c4e5f5-e8c7-4376-92f7-b8ac3528015c

2024-07-31 11:11 UTC, thestarsahil commented
from where the data fetching ?

2024-07-31 12:39 UTC, dhruv8433 commented
@thestarsahil 

I am using botPengiun where we can configure out ai chatbot for our website according our requirement

https://botpenguin.com/

2024-08-02 06:00 UTC, dhruv8433 commented
@thestarsahil 

please review it and if you need any modification please inform me

2024-08-02 15:18 UTC, thestarsahil commented
@dhruv8433 We are implementing Azure services in this project

2024-08-04 04:23 UTC, dhruv8433 commented
@thestarsahil 

check this i implemented Azure chatbot and make it more attractive by adding styles

https://github.com/user-attachments/assets/5775cbae-2467-4218-8e33-92ab5656fbd0

please check this and merge it

2024-08-04 12:31 UTC, dhruv8433 commented
@thestarsahil 

please sir review it and merge ir

2024-08-05 11:22 UTC, thestarsahil commented
Packages not uploaded properly

2024-08-05 11:22 UTC, thestarsahil commented
![Screenshot from 2024-08-05 16-52-44](https://github.com/user-attachments/assets/4d7e5563-b1bd-49eb-bfc5-db68d24d0a08)

2024-08-05 11:29 UTC, dhruv8433 commented
@thestarsahil 

please check now

![image](https://github.com/user-attachments/assets/6c665455-3a6a-484d-8de2-c2d145dc68b9)

2024-08-05 11:41 UTC, thestarsahil commented
Chatbot not should be login page 
![Screenshot from 2024-08-05 17-09-16](https://github.com/user-attachments/assets/6b9e089b-1996-49d7-b4f0-53be2c1f85c9)

On First Time its showing this 
![Screenshot from 2024-08-05 17-09-33](https://github.com/user-attachments/assets/9cfd8d3f-55c4-4f16-a379-4647ab097ab8)

On Closing and reopeing again its showing this 
![Screenshot from 2024-08-05 17-09-42](https://github.com/user-attachments/assets/efaa329a-f8cf-41ca-bd10-b0f3bc67d1a5)

2024-08-05 11:54 UTC, dhruv8433 commented
@thestarsahil 

please check now

https://github.com/user-attachments/assets/58431164-a4d8-4a1d-920d-f9aae49e6de1

2024-08-06 11:40 UTC, dhruv8433 commented
@thestarsahil 

when you become free please review it and merge it
also add level as per #1225

2024-08-06 14:23 UTC, thestarsahil commented
Resolve conflict and push again

2024-08-06 14:31 UTC, dhruv8433 commented
@thestarsahil 

now you can merge it

2024-08-07 07:07 UTC, dhruv8433 commented
@thestarsahil

when you become free please review it and merge it
also add level as per https://github.com/Counselllor/Counsellor-Web/issues/1225

2024-08-09 03:00 UTC, dhruv8433 commented
@thestarsahil 

i fetched upstream please sir check this and merge it

2024-08-09 07:30 UTC, thestarsahil commented
@dhruv8433 Check the review part i mentioned

2024-08-09 07:38 UTC, dhruv8433 commented
@thestarsahil 

i didn't get any changes in reviews section 
![image](https://github.com/user-attachments/assets/d12d14fd-0d53-496c-93ee-cd7a93804f00)

2024-08-09 08:14 UTC, thestarsahil requested changes

2024-08-09 08:15 UTC, thestarsahil commented on src/components/FAQs/FAQs.jsx
@dhruv8433

2024-08-09 08:15 UTC, thestarsahil commented on src/components/chatbot/Chatbot.jsx
@dhruv8433

2024-08-09 08:59 UTC, dhruv8433 commented
@thestarsahil 

i revert faqs and remove chat bot from login page 

![image](https://github.com/user-attachments/assets/641a0808-ee99-4030-8a41-cd9329202f05)

![image](https://github.com/user-attachments/assets/aef5ad08-9720-43f9-990f-9cf808ae9c62)

2024-08-09 09:00 UTC, dhruv8433 commented on src/components/chatbot/Chatbot.jsx
![Uploading image.png…]()

2024-08-09 12:26 UTC, dhruv8433 commented
@thestarsahil 

please review it and merge it

2024-08-09 12:52 UTC, thestarsahil commented
can you please resolve the problem for the last time

2024-08-09 13:16 UTC, dhruv8433 commented
@thestarsahil 

what i have to resolve

2024-08-09 13:23 UTC, dhruv8433 commented
@thestarsahil 

in my local build is success

![image](https://github.com/user-attachments/assets/f756e152-4c70-445f-9305-d4d335f5b412)

please tell me if you want any modification

2024-08-09 15:01 UTC, thestarsahil commented
![Screenshot from 2024-08-09 20-30-48](https://github.com/user-attachments/assets/70cefb33-2631-4940-a383-bd5597ecbaa3)

2024-08-09 16:22 UTC, dhruv8433 commented
@thestarsahil 

can you please try again i try to add upstream package here

2024-08-10 02:50 UTC, dhruv8433 commented
@thestarsahil 

Please sir merge thi
Today is last day and i am going back....

I completed and reviews package please merge it

2024-08-10 10:34 UTC, dhruv8433 commented
@thestarsahil 

please merge this

2024-08-10 14:05 UTC, thestarsahil commented
@dhruv8433 npm run build is not working on this PR kindly check once

2024-08-26 01:04 UTC, closed without merging