Add Forgot password Page
Counselllor/Counsellor-Web pull request #272
Opened 2023-07-15 14:54 UTC by SubhamB2003

# Description
solves #238 

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

2023-07-16 05:29 UTC, thestarsahil commented
![Screenshot 2023-07-16 105835](https://github.com/Counselllor/Counsellor-Web/assets/84167034/d31e07c3-461e-45cf-b61c-37d331cb2708)

Conflict occurs

2023-07-16 05:39 UTC, SubhamB2003 commented
@thestarsahil Please check.

2023-07-16 12:02 UTC, thestarsahil commented
Check the codebase again i marked it where to change

2023-07-16 12:57 UTC, SubhamB2003 commented
> Check the codebase again i marked it where to change

Hey, I removed below two-element
![image](https://github.com/Counselllor/Counsellor-Web/assets/94003231/19b94849-1f57-4f93-96be-aae2afb959b0)

2023-07-17 17:39 UTC, thestarsahil requested changes

2023-07-17 17:40 UTC, thestarsahil commented
You haven't checked yet properly , Have a looked on changes

2023-07-18 07:09 UTC, SubhamB2003 commented on src/components/Login/Login.jsx
> +import React, { useEffect, useState } from "react";
Hey, I am not changing anything I just format the document that's why it showing changes

2023-07-18 07:10 UTC, SubhamB2003 commented on src/components/Login/Login.jsx
> +        .then(() => {
same as this also

2023-07-20 17:37 UTC, SubhamB2003 commented
@thestarsahil Please review my pr

2023-07-21 12:11 UTC, thestarsahil commented
Hi Subham,

I just finished checking the codebase structure, and it looks great! Thank you so much for your wonderful contribution. Your work has been very helpful, and I appreciate your attention to detail.

I'm particularly impressed with the way you organized the code.
Overall, I'm very happy with your work.

2023-07-21 12:12 UTC, merged

2023-07-21 12:19 UTC, SubhamB2003 commented
> Hi Subham,
> 
> I just finished checking the codebase structure, and it looks great! Thank you so much for your wonderful contribution. Your work has been very helpful, and I appreciate your attention to detail.
> 
> I'm particularly impressed with the way you organized the code.
> Overall, I'm very happy with your work.

Thank you😊,
Happy to contribute