Added Links to The Career support Pages Navbar
Counselllor/Counsellor-Web pull request #951
Opened 2024-07-08 16:12 UTC by RadhikaMalpani1702

# Description
Hey @thestarsahil 

I have added the links to the Career support page navbar 
Additionally, there was log in button instead of log out so I have removed it and added log out functionality

## Fixes #944 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/Counselllor/Counsellor-Web/assets/163530398/a454dff1-2be2-429f-9650-5383a54c030b

## Checklist

- [X] Tests have been added or updated to cover the changes
- [X] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

2024-07-08 16:32 UTC, thestarsahil requested changes

2024-07-08 16:32 UTC, thestarsahil commented on src/components/Navbar/Navbar.jsx
> +      <MenuItem href="/dashboard">Top Universities</MenuItem>
<MenuItem href="#">Top Universities</MenuItem>

2024-07-08 18:40 UTC, RadhikaMalpani1702 commented
@thestarsahil Made the changes

2024-07-11 09:09 UTC, RadhikaMalpani1702 commented
@thestarsahil Please merge this PR

2024-07-11 14:40 UTC, thestarsahil commented
Its Done Already !

2024-07-12 13:01 UTC, closed without merging